### ISSUE TITLE
use the nullable type where possible

### ISSUE THREAD

**Issue by bitkid** [wuan/assertj-core-kotlin#1]
i have the situation that i have a class A with a field
val map : Map<String,String>?

so this won't compile
assertThat(A().map).isNull()

so i guess
fun <K, V> assertThat(actual: Map<K, V>?) = MapAssert(actual)

would be better

**Comment by wuan** [comment]
Thanks for reporting.

Unfortunately this will not be possible.

If we apply your proposed change, we have to modify the other methods as well, because of reasons of symmetry. After doing this, we will get back to the problem which originally led to the creation of this interface project. Kotlin cannot determine the correct method for quasi untyped null values.

The workaround is, to check optional values for null before using a mathing `assertThat` method.
